#Direct the main healthcheck to port 8000
#Direct the face-bokeh to port 8001
#Direct the face-emotion to port 8002

version: '3'
services:
  face-bokeh:
    build: ./face-bokeh
    ports:
      - '8001:8000'
  face-emotion:
    build: ./face-emotion
    ports:
      - '8002:8000'
  myapp:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - face-bokeh
      - face-emotion
